using Cinemachine;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CamaerManager : MonoBehaviour
{
    public CinemachineTargetGroup target;
    public CinemachineVirtualCamera vCam;
    float curSize; // 汰 촾콜쐑
    float zoomSize; // 점킨 촾첉,촾쮅 콜쐑
    bool zoom = false; // 촾 쫞 찔쥁

    void Awake()
    {
        vCam = GetComponent<CinemachineVirtualCamera>();
        curSize = vCam.m_Lens.OrthographicSize;
    }

    void Update()
    {
        if (zoom)
        {
            if (zoomSize > curSize) // 촾쮅
            {
                vCam.m_Lens.OrthographicSize += 0.05f;
                if (vCam.m_Lens.OrthographicSize >= zoomSize)
                {
                    zoom = false;
                    vCam.m_Lens.OrthographicSize = Mathf.FloorToInt(vCam.m_Lens.OrthographicSize);
                    curSize = zoomSize;
                }
            }
            else if (zoomSize < curSize) // 촾첉
            {
                vCam.m_Lens.OrthographicSize -= 0.05f;
                if (vCam.m_Lens.OrthographicSize <= zoomSize)
                {
                    zoom = false;
                    vCam.m_Lens.OrthographicSize = Mathf.FloorToInt(vCam.m_Lens.OrthographicSize);
                    curSize = zoomSize;
                }
            }
        }
    }

    public void Zoom(float size)
    {
        zoomSize = size;
        zoom = true;
    }
}
